#pragma once

//#define REPORT_FS_LF_ERRORS
//#define DEBUG_ALL_CHANNEL_DATA
//#define DEBUG_WAVE_CHANNEL_DATA
//#define DEBUG_WAVE_MONITORING_TYPE
//#define REPORT_BAD_FRAME_ERRORS



#if defined (REPORT_FS_LF_ERRORS)
#warning DONT FLASH WITH REPORT_ERRORS ACTIVATED
#endif

#if defined (DEBUG_ALL_CHANNEL_DATA)
#warning DONT FLASH WITH DEBUG_DATA ACTIVATED
#endif

#if defined (DEBUG_WAVE_CHANNEL_DATA)
#warning DONT FLASH WITH DEBUG_DATA ACTIVATED
#endif

#if defined (DEBUG_WAVE_MONITORING_TYPE)
#warning DONT FLASH WITH DEBUG_DATA ACTIVATED
#endif

#if defined (REPORT_BAD_FRAME_ERRORS)
#warning DONT FLASH WITH DEBUG_DATA ACTIVATED
#endif
